CREATE TABLE `agreements` (
	`id` int AUTO_INCREMENT NOT NULL,
	`contractReference` varchar(64) NOT NULL,
	`clientName` text NOT NULL,
	`siteAddress` text NOT NULL,
	`city` varchar(255) NOT NULL,
	`postcode` varchar(20) NOT NULL,
	`contactName` varchar(255) NOT NULL,
	`position` varchar(255),
	`telephone` varchar(50) NOT NULL,
	`email` varchar(320) NOT NULL,
	`startDate` timestamp NOT NULL,
	`endDate` timestamp NOT NULL,
	`contractDuration` varchar(50) NOT NULL,
	`serviceFrequency` varchar(50) NOT NULL,
	`accessRequirements` text,
	`servicesIncluded` text NOT NULL,
	`specialRequirements` text,
	`serviceFee` decimal(10,2) NOT NULL,
	`maintenanceFee` decimal(10,2) NOT NULL,
	`additionalFee` decimal(10,2) NOT NULL DEFAULT '0.00',
	`subtotal` decimal(10,2) NOT NULL,
	`vat` decimal(10,2) NOT NULL,
	`total` decimal(10,2) NOT NULL,
	`paymentSchedule` varchar(50) NOT NULL,
	`clientSignatureUrl` text NOT NULL,
	`clientPrintName` varchar(255) NOT NULL,
	`clientSignedAt` timestamp NOT NULL,
	`companySignatureUrl` text NOT NULL,
	`companyPrintName` varchar(255) NOT NULL,
	`companySignedAt` timestamp NOT NULL,
	`termsAccepted` int NOT NULL DEFAULT 1,
	`status` enum('pending','active','completed','cancelled') NOT NULL DEFAULT 'active',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	`submittedBy` int,
	CONSTRAINT `agreements_id` PRIMARY KEY(`id`),
	CONSTRAINT `agreements_contractReference_unique` UNIQUE(`contractReference`)
);
--> statement-breakpoint
CREATE TABLE `equipment` (
	`id` int AUTO_INCREMENT NOT NULL,
	`agreementId` int NOT NULL,
	`quantity` int NOT NULL,
	`type` varchar(255) NOT NULL,
	`size` varchar(100) NOT NULL,
	`location` text NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `equipment_id` PRIMARY KEY(`id`)
);
